version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports: 
      - 9876:5432 # acesso usando 9876 aqui na máquina
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTRGRES_DB=next-saas